import fs from 'node:fs';
import assert from 'node:assert/strict';
const root = new URL('.', import.meta.url).pathname;
const worker=fs.readFileSync(root+'worker.js','utf8');
const schema=fs.readFileSync(root+'schema.sql','utf8');
const env=fs.readFileSync(root+'.env.example','utf8');
assert.match(worker,/https:\/\/api\.resend\.com\/emails/);
assert.match(worker,/RESEND_API_KEY/);
assert.match(worker,/ORDER_EMAIL_TO/);
assert.match(worker,/ORDER_EMAIL_FROM/);
assert.match(worker,/https:\/\/control\.msg91\.com\/api\/v5\/flow/);
assert.match(worker,/MSG91_AUTHKEY/);
assert.match(worker,/MSG91_SMS_TEMPLATE_ID/);
assert.match(worker,/MSG91_SMS_SENDER_ID/);
assert.match(worker,/ORDER_SMS_TO/);
assert.match(worker,/async function notifyPaidOrder/);
assert.match(worker,/notifyPaidOrder\(env,local\.customer_order_id,paymentId\)/);
assert.match(worker,/customer_orders SET status='PAID'/);
assert.match(worker,/order_notifications/);
assert.match(schema,/CREATE TABLE IF NOT EXISTS order_notifications/);
assert.match(schema,/UNIQUE\(customer_order_id, channel\)/);
assert.match(env,/ORDER_EMAIL_TO=contact@khushifoodproducts\.in/);
assert.match(env,/ORDER_SMS_TO=8073455939/);
assert.ok(!worker.includes('wYX4qMDdtwP9kgFjVt8LHMbQ'),'Razorpay secret must not be hardcoded');
assert.ok(!worker.includes('rzp_test_TY5hErlakFX1u2'),'Razorpay test key must not be hardcoded');
console.log('ORDER NOTIFICATION QA PASSED');
